# Default values for foreman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sslSecret: foreman-ssl-certs

image:
  repository: quay.io/foreman
  pullPolicy: IfNotPresent
  name: foreman
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.18"

apache:
  enabled: false
  extraEnv:
    APACHE_RUN_DIR: /usr/local/apache2/htdocs
  image:
    repository: registry.example.com/foreman
    pullPolicy: IfNotPresent
    name: foreman-apache
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3.18"

curl_image: alpine/curl

PodSecurityContext:
  runAsNonRoot: true

SecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

foreman:
  resources: {}
  cache:
    size: "50Mi"
  extraEnv:
    FOREMAN_PUMA_THREADS_MAX: 2
    FOREMAN_PUMA_THREADS_MIN: 2
    FOREMAN_PUMA_WORKERS: 1
  fqdn:
    - ""

  hsts_enabled: true
  logging:
    level: "info"
    type: "stdout"
  loggers:
    app: true
    ldap: false
    permissions: false
    sql: false
    background: true
    dynflow: true
    proxy: true
    notifications: true
  startup_delay: 20

  redis_urls: []
  require_ssl: false
  unattended: true

housekeeping:
  enabled: true
  days_to_retain: 30
  failedJobsHistoryLimit: 2
  resources: {}
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  foreman_tasks:
    enabled: true
    dry_run: false

dynflow:
  redis_url: "redis://localhost:6379/1"
  enabled: true
  orchestrator:
    extraEnv: {}
  worker:
    amount: 1
    concurrency: 10
    extraEnv: {}

metrics:
  enabled: false
  labels: {}
  ServiceMonitor: false

db:
  adapter: postgresql
  database: foreman
  host: localhost
  password: foreman
  pool: 5
  username: foreman
  existingSecretName: ""
  existingSecretKey: password

encryptionKey:
  existingSecretName: ""
  secretKey: encryption_key.rb

plugins:
  default_hostgroup: ""
  openstack_hostgroup: "Null/Base"
  foreman_tasks:
    logging:
      dynflow: true
      action: true

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
