apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman-proxy.fullname" . }}-config
  labels:
    {{- include "foreman-proxy.labels" . | nindent 4 }}
data:
  settings.yml: |
    ---
    :bind_host: 0.0.0.0
    :daemon: false
    :{{ .Values.config.scheme }}_port: 8000

    # SSL certificates
    :ssl_certificate: /etc/foreman-proxy/ssl/{{ include "foreman-proxy.fullname" . }}.cert.pem
    :ssl_private_key: /etc/foreman-proxy/ssl/{{ include "foreman-proxy.fullname" . }}.key.pem
    :ssl_ca_file: /etc/foreman-proxy/ssl/ca.pem

    # Logs
    :log_file: STDOUT
    :log_level: INFO
    :log_buffer: 2000
    :log_buffer_errors: 1000

    {{- with .Values.config.settings }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
