apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foreman-proxy.fullname" . }}-ssh-config
  labels:
    {{- include "foreman-proxy.labels" . | nindent 4 }}
data:
  DisableKnownHostsFile.conf: |
    Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        GlobalKnownHostsFile /dev/null
