{{- if not .Values.encryptionKey.existingSecretName }}
{{- $secretName := printf "%s-encryption-key" (include "foreman.fullname" .) -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $existingKey := "" -}}
{{- if $secret }}
{{- $existingKey = index $secret.data .Values.encryptionKey.secretKey | b64dec -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "foreman.foreman.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.encryptionKey.secretKey }}: |
    {{- if $existingKey }}
    {{- $existingKey | nindent 4 }}
    {{- else }}
    module EncryptionKey
      ENCRYPTION_KEY = '{{ randAlphaNum 32 | lower }}'
    end
    {{- end }}
{{- end }}
