{{- if .Values.apache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "foreman.fullname" . }}-http
  labels:
    {{- include "foreman.foreman.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "foreman.foreman.selectorLabels" . | nindent 4 }}
{{- end -}}
